modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
[[mods]]
modId="l2damagetracker"
version="${file.jarVersion}" #mandatory
displayName="L2 Damage Tracker" #mandatory
logoFile="l2damagetracker.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.l2damagetracker]]
    modId="forge"
    mandatory=true
    versionRange="[46.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2damagetracker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2damagetracker]]
    modId="l2library"
    mandatory=true
    versionRange="[2.4.0-a0,)"
    ordering="AFTER"
    side="BOTH"